server:
  error:
    whitelabel:
      enabled: true # Configuración de la página de error, false -> la de tomcat
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advfot?useSSL=false # JDBC url of the database, configurado para que no muestre adventencia de conexión insegura
    username: root # Login user of the database.
    password: root # Login password of the database.
  jpa:
    show-sql: true # Muestra las sentecias sql en pantalla cuando se realizan.
    hibernate:
      ddl-auto: update # Actualiza las tablas según las entidades creadas
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy # Forma de realizar las consultas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # Dialecto que usa al realizar las consultas
  thymeleaf:
    cache: false # Indica que no guarde las plantillas en la caché